
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xujnipsqsrjstmwbvulq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1am5pcHNxc3Jqc3Rtd2J2dWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTYwNTMsImV4cCI6MjA2MTU5MjA1M30.jUNjeSFLtKiMsgFBAL1Os-v1bly6uP47qEqQKHjidB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
